version: 3.0.0-alpha-{build}

configuration: Release

image: Visual Studio 2017

services:
  - mssql2017

dotnet_csproj:
  patch: true
  file: '**\*.csproj;**\*.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

nuget:
  project_feed: true

before_build:
  - cmd: dotnet --info
  - cmd: dotnet restore --verbosity Minimal

build_script:
  - cmd: dotnet build src\FluentProjections.Persistence.SQL --configuration %CONFIGURATION%

after_build:
  - cmd: dotnet pack src\FluentProjections.Persistence.SQL --configuration %CONFIGURATION% --include-symbols --no-build --output ..\..\nupkgs /p:PackageVersion=%APPVEYOR_BUILD_VERSION%

test_script:
  - cmd: dotnet test tests\FluentProjections.Persistence.SQL.Tests\FluentProjections.Persistence.SQL.Tests.csproj --configuration %CONFIGURATION%

artifacts:
  - path: nupkgs\*.nupkg
